name: temp-20250114
services:
  app:
    image: temp-20250114:latest
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
    entrypoint: ./docker/php-fpm-nginx/script.sh
    #    entrypoint: ./docker/api/script.sh
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      - maria
###> doctrine/doctrine-bundle ###
  maria:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=app
#    ports:
#      - "8021:3306"
    volumes:
      - database_data:/var/lib/mariadb/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
